Add ContentView
DeveloperAcademy-POSTECH/MC3-Team3-DaejeonPeople pull request #11
Opened 2023-07-13 09:08 UTC by Miiirona

#10

2023-07-13 13:46 UTC, poodlepoodle submitted a review, later dismissed
👍👍

2023-07-14 07:32 UTC, ckyeon requested changes

2023-07-14 07:32 UTC, ckyeon commented on AllerView/ContentView.swift
> +    }
`Chip` 컴포넌트가 ProductDetailView에서도 사용하는 컴포넌트라 외부 파일로 빼주셔야 할 것 같아요!!

2023-07-14 07:32 UTC, ckyeon commented on AllerView/ContentView.swift
> +//                        NavigationLink(destination: CameraView()) {
필요없는 주석은 지워주시면 좋을 것 같아요!

2023-07-14 07:32 UTC, ckyeon commented on AllerView/ContentView.swift
> +                ZStack{
`ZStack`과 `{` 사이에 공백이 없는데 이 부분은 [xcode formatter](https://github.com/Jintin/Swimat)를 사용하시면 도움될 것 같아요~

2023-07-14 07:32 UTC, ckyeon commented on AllerView/ContentView.swift
> +                ZStack{
설치 포스트 입니다~
https://velog.io/@ashappyasikonw/Code-Formatting-In-Xcode

2023-07-14 07:35 UTC, migusdn submitted a review, later dismissed
😃

2023-07-15 09:12 UTC, snacknam submitted a review, later dismissed
good🙂

2023-07-17 05:53 UTC, ckyeon submitted a review, later dismissed

2023-07-17 05:59 UTC, merged